version: '3.8'

networks:
  fluxdb:
    driver: bridge

services: 
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    expose:
      - "3306"
    ports:
      - 3306:3306
    networks:
      - fluxdb 
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
  operator:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flux-operator-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    ports:
      - 3307:3307
    networks:
      - fluxdb 
volumes: 
  db-config:
  db-data: